// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC_SULJuga3mwUOHDt6DzqWOPjhSBnTUY',
    appId: '1:1088489529502:web:e36649df102a50c78ddb8f',
    messagingSenderId: '1088489529502',
    projectId: 'datbdd-2cf65',
    authDomain: 'datbdd-2cf65.firebaseapp.com',
    storageBucket: 'datbdd-2cf65.firebasestorage.app',
    measurementId: 'G-HQ14GMRNTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6LtvGEXGhckiaAj5ne7nJ12t5cUaaiSw',
    appId: '1:1088489529502:android:2b35df46820912678ddb8f',
    messagingSenderId: '1088489529502',
    projectId: 'datbdd-2cf65',
    storageBucket: 'datbdd-2cf65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNWknLBxka2ZIEP6DiUhdSeLKnUAL3zRU',
    appId: '1:1088489529502:ios:0a805b9ff6bc70e98ddb8f',
    messagingSenderId: '1088489529502',
    projectId: 'datbdd-2cf65',
    storageBucket: 'datbdd-2cf65.firebasestorage.app',
    iosBundleId: 'com.example.datbdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNWknLBxka2ZIEP6DiUhdSeLKnUAL3zRU',
    appId: '1:1088489529502:ios:0a805b9ff6bc70e98ddb8f',
    messagingSenderId: '1088489529502',
    projectId: 'datbdd-2cf65',
    storageBucket: 'datbdd-2cf65.firebasestorage.app',
    iosBundleId: 'com.example.datbdd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC_SULJuga3mwUOHDt6DzqWOPjhSBnTUY',
    appId: '1:1088489529502:web:1e6596a57cbd55a78ddb8f',
    messagingSenderId: '1088489529502',
    projectId: 'datbdd-2cf65',
    authDomain: 'datbdd-2cf65.firebaseapp.com',
    storageBucket: 'datbdd-2cf65.firebasestorage.app',
    measurementId: 'G-Y0THBT7QB0',
  );
}
